### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by mikefidel** [ndextools/ndex-morphcx#1]
Enter the following command-line: "java -jar morphcx.jar -c tsv -i Fig._2_HPV-human_Protein_Network_Map.json"  The program terminates with the following message:
java.lang.Exception: java.lang.IllegalStateException: attempt to return list of values as single value: "[HPV-31_E6]" in attribute Matching.Attribute.1
	at org.ndextools.morphcx.tables.CSVRoot.execute(CSVRoot.java:30)
	at org.ndextools.morphcx.shared.Dispatcher.dispatch(Dispatcher.java:30)
	at org.ndextools.morphcx.MorphCX.dispatchByOperation(MorphCX.java:45)
	at org.ndextools.morphcx.MorphCX.main(MorphCX.java:26)
Caused by: java.lang.IllegalStateException: attempt to return list of values as single value: "[HPV-31_E6]" in attribute Matching.Attribute.1
	at org.ndexbio.cxio.aspects.datamodels.AbstractAttributesAspectElement.getValue(AbstractAttributesAspectElement.java:128)
	at org.ndextools.morphcx.tables.Webapp.collectNodeAttributes(Webapp.java:127)
	at org.ndextools.morphcx.tables.Webapp.morphThisNiceCX(Webapp.java:84)
	at org.ndextools.morphcx.tables.CSVRoot.execute(CSVRoot.java:28)
	... 3 more

**Comment by mikefidel** [comment]
Fixed.
