### ISSUE TITLE
NullPointerException in Webapp.collectNodeAttributes(line 130)

### ISSUE THREAD

**Issue by mikefidel** [ndextools/ndex-morphcx#3]
Network UUID: 04c0a7e8-af92-11e7-94d3-0ac135e8bacf : ITCR_Connectivity_Map

Application invoked using the following command-line:
java -jar morphcx.jar -c tsv -i ITCR_Connectivity_Map.json

Stacktrace when application abnormally terminates:
java.lang.Exception: java.lang.NullPointerException
	at org.ndextools.morphcx.tables.CSVRoot.execute(CSVRoot.java:30)
	at org.ndextools.morphcx.shared.Dispatcher.dispatch(Dispatcher.java:49)
	at org.ndextools.morphcx.MorphCX.dispatchByOperation(MorphCX.java:60)
	at org.ndextools.morphcx.MorphCX.main(MorphCX.java:29)
Caused by: java.lang.NullPointerException
	at org.ndextools.morphcx.tables.Webapp.collectNodeAttributes(Webapp.java:130)
	at org.ndextools.morphcx.tables.Webapp.morphThisNiceCX(Webapp.java:84)
	at org.ndextools.morphcx.tables.CSVRoot.execute(CSVRoot.java:28)
	... 3 more

**Comment by mikefidel** [comment]
Investigation reveals this network does not contain any node attributes.  The present code base expects there to be node attributes.

Action: refactor code base so that neither node nor edge attributes have to exist in a cx network.

**Comment by mikefidel** [comment]
Fixed in UUID: 287a7d5c6d03d6a3868d19b6e303d403af582b11
